NBILicenseProjectMVC/Controllers/ApplicantController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using NBILicenseProjectMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;


namespace NBILicenseProjectMVC.Controllers
{
    public class ApplicantController : Controller
    {
        private readonly IConfiguration _config;
        //private readonly IWebHostEnvironment _webHostingEnviroment;
        private readonly string _apiUrl;
        public static HttpClient Client = null;

        public ApplicantController(IConfiguration config)
        {
            //_context = context;
            _config = config;
            _apiUrl = _config.GetValue<string>("WebApiUrl");
            if (Client == null)
            {
                Client = new HttpClient();
                Client.Timeout = TimeSpan.FromSeconds(_config.GetValue<int>("WebApiTimeOut"));
                Client.BaseAddress = new Uri(_apiUrl);

            }

        }

        // GET: Applicant
        public async Task<IActionResult> Index(string searchBy, string searchValue, string sortOrder)
        {
            
            IList<Applicant> listapplicants = null;
            try
            {
                var responseTask = Client.GetAsync("api/Applicant");
                responseTask.Wait();
                var result = responseTask.Result;



                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<Applicant>>();
                    readTask.Wait();
                    listapplicants = readTask.Result;
                }

            }
            catch (Exception ex)
            {
                Response.StatusCode = 400;
                return View("BadRequest");
            }

            //Search functionalities

            try
            {
                if (listapplicants.Count == 0)
                {
                    TempData["InfoMessage"] = "Your database has no entry data.";
                }
                else
                {
                    if (string.IsNullOrEmpty(searchValue))
                    {
                        TempData["InfoMessage"] = "PLease provide search value";
                        return View(listapplicants);
                    }
                    else
                    {
                        if (searchBy.ToLower() == "firstname")
                        {
                            var searchAuthorName = listapplicants.Where(x => x.Firstname.ToLower().Contains(searchValue.ToLower()));
                            return View(searchAuthorName);
                        }
                        else if (searchBy.ToLower() == "lastname")
                        {
                            var searchTitle = listapplicants.Where(x => x.Lastname.ToLower().Contains(searchValue.ToLower()));
                            return View(searchTitle);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Response.StatusCode = 400;
                return View("BadRequest");
            }
            
            //Sort

            try 
            {
                ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "Lastname" : "";
                SortFilter sortFilter = new SortFilter();

                if (sortFilter.sortBy == "Lastname")
                {
                    var sortlastname = listapplicants.Where(x => x.Lastname.StartsWith(sortOrder));
                    sortlastname.OrderBy(x => x.Lastname);
                    return View(sortlastname.ToList());
                }
                
            }
         
            catch (Exception ex)
            {
                Response.StatusCode = 400;
                return View("BadRequest");
            }

           return View(listapplicants);
        }


        // GET: Applicant/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                Response.StatusCode = 404;
                return View("NotFound", id.Value);
            }

            var applicant = GetApplicant(id.Value);
            if (applicant == null)
            {
                Response.StatusCode = 404;
                return View("NotFound", id.Value);
            }

            return View(applicant);
        }

        // GET: Applicant/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Applicant/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,BranchName,Date,ValidId,ApplicantPicture,Lastname,Firstname,Middlename,Birthdate,Gender,CivilStatus,EducationalAttainment,LandlineNumber,MobileNumber,EmailAddress,Complexion,Peculiarities,Religion,Height,Weight,HusbandOrWifeName,FatherName,FatherBirthplace,MotherName,MotherBirthplace")] Applicant applicant)
        {
            if (ModelState.IsValid)
            {
                var responseTask = Client.PostAsJsonAsync("api/Applicant", applicant);
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(applicant);
        }

        // GET: Applicant/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                Response.StatusCode = 404;
                return View("NotFound", id.Value);
            }

            var applicant = GetApplicant(id.Value);
            if (applicant == null)
            {
                Response.StatusCode = 404;
                return View("NotFound", id.Value);
            }
            return View(applicant);
        }

        // POST: Applicant/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BranchName,Date,ValidId,ApplicantPicture,Lastname,Firstname,Middlename,Birthdate,Gender,CivilStatus,EducationalAttainment,LandlineNumber,MobileNumber,EmailAddress,Complexion,Peculiarities,Religion,Height,Weight,HusbandOrWifeName,FatherName,FatherBirthplace,MotherName,MotherBirthplace")] Applicant applicant)
        {
            if (id != applicant.Id)
            {
                Response.StatusCode = 404;
                return View("NotFound", id);
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //_context.Update(applicant);
                    //await _context.SaveChangesAsync();
                    //HTTP GET
                    var responseTask = Client.PutAsJsonAsync($"api/Applicant/{id}", applicant);
                    responseTask.Wait();
                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        Response.StatusCode = 404;
                        return View("NotFound", id);
                    }
                }
                catch (Exception ex)
                {
                    Response.StatusCode = 400;
                    return View("BadRequest");
                }  
            }
            return View(applicant);
        }

        // GET: Applicant/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                Response.StatusCode = 404;
                return View("NotFound", id.Value);
            }

            var applicant = GetApplicant(id.Value);
            if (applicant == null)
            {
                Response.StatusCode = 404;
                return View("NotFound", id.Value);
            }

            return View(applicant);
        }

        // POST: Applicant/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try 
            {
                var responseTask = Client.DeleteAsync($"api/Applicant/{id}");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception)
            {
                Response.StatusCode = 400;
                return View("BadRequest");
            }
            return RedirectToAction(nameof(Delete), id);


        }

        //private bool ApplicantExists(int id)
        //{
        //    return _context.Applicant.Any(e => e.Id == id);
        //}

        private Applicant GetApplicant(int id)
        {
            Applicant applicant = null;
            var responseTask = Client.GetAsync($"api/Applicant/{id}");
            responseTask.Wait();

            var result = responseTask.Result;
            if (result.IsSuccessStatusCode)
            {
                var readTask = result.Content.ReadAsAsync<Applicant>();
                readTask.Wait();
                applicant = readTask.Result;
            }
            return applicant;
        }
    }
}

NBILicenseProjectMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using NBILicenseProjectMVC.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using static System.Reflection.Metadata.BlobBuilder;

namespace NBILicenseProjectMVC.Controllers
{
   
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConfiguration _config;
        private readonly string _apiUrl;
        public static HttpClient Client = null;

        public HomeController(ILogger<HomeController> logger, IConfiguration config)
        {
            _logger = logger;
            _config = config;
            _apiUrl = _config.GetValue<string>("WebApiUrl");
            
            if (Client == null)
            {
                Client = new HttpClient();
                Client.Timeout = TimeSpan.FromSeconds(_config.GetValue<int>("WebApiTimeOut"));
                Client.BaseAddress = new Uri(_apiUrl);
            }
        }

        public IActionResult Index()
        {
            // return View();
            IList<Applicant> listapplicants = null;
            
            try
            {
                var responseTask = Client.GetAsync("api/Applicant");
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<Applicant>>();
                    readTask.Wait();
                    listapplicants = readTask.Result; 
                }

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                //return BadRequest("Application Error");
                return View("BadRequest");
            }
            return View(listapplicants);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult NotFound()
        {
            return View();
        }
    }
}

NBILicenseProjectMVC/Views/Home/Index.cshtml
@model IEnumerable<NBILicenseProjectMVC.Models.Applicant>
@{
    ViewData["Title"] = "Index";
}

<br />
<h1 style="text-align:center">Home Page</h1>
<br />
<br />
<hr />
<div style="text-align:left">
    @using (Html.BeginForm("Index", "Applicant", FormMethod.Get))
    {
        <table>
            <tr>
                <td>
                    @Html.RadioButton("searchBy", "Firstname", true)
                    <text> First Name</text>
                    @Html.RadioButton("searchBy", "Lastname")
                    <text> Last Name</text>
                </td>
            </tr>
            <tr>
                <td>
                    @Html.TextBox("searchValue", null, new{Class="form-control",placeholder="Enter First/Last Name"})
                </td>
                <td>
                    <input type="submit" value="Search" class="btn btn-success" />
                </td>
                <td> &nbsp; </td>
            </tr>

        </table> <br />
    }
</div>

<br>
<div class="d-flex justify-content-center table table-hover table-striped">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ApplicantPicture)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Lastname)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Firstname)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Middlename)
                </th>
                <th>
                        @Html.DisplayNameFor(model => model.Birthdate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BranchName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ValidId)
                <th>
                        @Html.DisplayNameFor(model => model.Gender)
                </th>
                <th>
                        @Html.DisplayNameFor(model => model.CivilStatus)
                </th>
                <th>
                        @Html.DisplayNameFor(model => model.EducationalAttainment)
                </th>
                <th>
                        @Html.DisplayNameFor(model => model.LandlineNumber)
                </th>
                <th>
                        @Html.DisplayNameFor(model => model.MobileNumber)
                </th>
                <th>
                        @Html.DisplayNameFor(model => model.EmailAddress)
                </th>
                <th>
                        @Html.DisplayNameFor(model => model.Complexion)
                </th>
                <th>
                        @Html.DisplayNameFor(model => model.Peculiarities)
                </th>
                <th>
                        @Html.DisplayNameFor(model => model.Religion)
                </th>
                <th>
                        @Html.DisplayNameFor(model => model.Height)
                </th>
                <th>
                        @Html.DisplayNameFor(model => model.Weight)
                </th>
                <th>
                        @Html.DisplayNameFor(model => model.HusbandOrWifeName)
                </th>
                <th>
                        @Html.DisplayNameFor(model => model.FatherName)
                </th>
                <th>
                        @Html.DisplayNameFor(model => model.FatherBirthplace)
                </th>
                <th>
                        @Html.DisplayNameFor(model => model.MotherName)
                </th>
                <th>
                        @Html.DisplayNameFor(model => model.MotherBirthplace)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr style="font-family:'Segoe UI'; font-size: 16px; font-weight:400;color:maroon">
                    <td>
                        <img src="@item.ApplicantPicture" class="rounded mx-auto d-block" style="overflow: hidden; position: relative; width:100px; height:100px;" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Lastname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Firstname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Middlename)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Birthdate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BranchName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ValidId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Gender)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CivilStatus)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EducationalAttainment)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LandlineNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MobileNumber)
                    </td>
                    <td class="text-justify" id="textbox" style="width:80px; height:0px; word-wrap: break-word">
                        @Html.DisplayFor(modelItem => item.EmailAddress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Complexion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Peculiarities)
                    </td>
                    <td class="text-justify" id="textbox" style="width:80px; height:60px; word-wrap: break-word">
                        @Html.DisplayFor(modelItem => item.Religion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Height)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Weight)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HusbandOrWifeName)
                    </td>
                    <td class="text-justify" id="textbox" style="width:100px; height:80px; word-wrap: break-word">
                        @Html.DisplayFor(modelItem => item.FatherName)
                    </td>
                    <td class="text-justify" id="textbox" style="width:100px; height:80px; word-wrap: break-word">
                        @Html.DisplayFor(modelItem => item.FatherBirthplace)
                    </td>
                    <td class="text-justify" id="textbox" style="width:100px; height:80px; word-wrap: break-word">
                        @Html.DisplayFor(modelItem => item.MotherName)
                    </td>
                    <td class="text-justify" id="textbox" style="width:100px; height:80px; word-wrap: break-word">
                        @Html.DisplayFor(modelItem => item.MotherBirthplace)
                    </td>
                    <td>
                        <a class="btn btn-success" asp-controller="Applicant" asp-action="Details" asp-route-id="@item.Id">Details</a>
                    </td>

                </tr>
            }
        </tbody>
    </table>

</div>